name: sky_cast
description: A project for sky status (Weather).
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

  # HydratedBloc allows us to persist application state when the app is closed and reopened.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hydrated_bloc: ^9.0.0
  flutter_bloc: ^8.1.1
  google_fonts: ^3.0.1
  json_annotation: ^4.8.0
  equatable: ^2.0.5
  path_provider: ^2.0.12
  weather_repository:
    path: packages/weather_repository
  shared_preferences: ^2.0.17
  get_it: ^7.2.0
  flutter_lints: ^2.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  flutter_launcher_icons: ^0.11.0
  freezed: ^2.3.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/weather_icon.png"
  web:
    generate: true
    image_path: "assets/weather_icon.png"
  windows:
    generate: true
    image_path: "assets/weather_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/weather_icon.png"




  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
